function [forceStruct] = CalculateForces( aBolt,attachmentPlate,bearingAA,bearingCasingEF,bottomBracket_L,bottomBracket_R...
                                                    ,exoThigh,uBar,exoShank,foamThigh,gasSpring,gasSpringBolts...
                                                    ,hipFlexExBearing,hipMember,hipMember2,hipSpring,hipStopper,hipStopperPin...
                                                    ,keys,kneePin,pawl,foamShank,pawlPin,pawlString,pawlSpring,plungerCasingEF...
                                                    ,plungerEF,plungerScrewEF,ratchet,shaftAA,shelf,thighScrew,shankScrew,topBracket_L...
                                                    ,topBracket_R,cBoot... 
                                                    ,flxExtHip_AngAcceleration,shank_AccelerationX,shank_AccelerationY,shank_AngAcceleration...
                                                    ,foot_AccelerationX,foot_AccelerationY,A4Hip_Acceleration,greaterTrochanter_AccelerationX...
                                                    ,greaterTrochanter_AccelerationY,com_Acceleration,abdAddHip_AngAcceleration,momentHip...
                                                    ,momentKnee,thigh_AccelerationX,thigh_AccelerationY,A4Hip_Angle,hip_Moment,ground_ReactionX...
                                                    ,ground_ReactionY,ankle_Angle,A3Thigh_AngAcceleration...
                                                    ,UserM) 
%Calculate Forces
%Written by: Matthew Choi
%Last updated: Nov. 22, 2019
%Input: All objects and accelerations necessary to calculate their respective forces
%Output: Force strucutre containing components and their derivative forces.
%The forces are across 70 frames, so they must be mapped across 100 frames
%(ie. gait %) externally.
%Description: Takes the input objects and calls their force functions.
%Stores the results into a force structure.
%Notes: Merged with Megan's main code,finish debugging and check over with mainMEGAN from old code

%% Component Names %%
components = {'aBolt1' 'attachmentPlate1' 'bearingAA1' 'bearingCasingEF1' 'bottomBracket_L1' 'bottomBracket_R1' 'exoThigh1' 'uBar1'...
                                                    'exoShank1' 'foamThigh1' 'gasSpring1' 'gasSpringBolts1' 'hipFlexExBearing1'...
                                                    'hipMember1' 'hipMember21' 'hipString1' 'hipStopper1' 'hipStopperPin1' 'keys1'...
                                                    'kneePin1' 'pawl1' 'foamShank1' 'pawlPin1' 'pawlString1' 'plungerCasingEF1' 'plungerEF1'...
                                                    'plungerScrewEF1' 'ratchet1' 'shaftAA1' 'shelf1' 'thighScrew1' 'shankScrew1' 'topBracket_L1'...
                                                    'topBracket_R1' 'cBoot1'};
                                                
%% Force Names %% (not used)
forceNames = {'forceGSYmax' 'forceGSXL' 'forceGSYL' 'forceGSXR' 'forceGSYR' 'forceGasSpringBracket1_x_R'...
    'forceGasSpringBracket1_y_R' 'forceGasSpringBracket1_x_L' 'forceGasSpringBracket1_y_L'...
    'forceGasSpringBolt1_x_R' 'forceGasSpringBolt1_y_R' 'forceGasSpringBolt1_x_L' 'forceGasSpringBolt1_y_L'...
    'forceGasSpringBolt2_x_R' 'forceGasSpringBolt2_y_R' 'forceGasSpringBolt2_x_L' 'forceGasSpringBolt2_x_L'...
    'forceBottom_x_R' 'forceBottom_y_R' 'forceBottom_x_L' 'forceBottom_y_L' 'FL1' 'FL2'...
    'forceMember2_R' 'torqueBearingABD_R' 'forceBushingY_R' 'forceCasingAbdY_R'...
    'forceHip_R' 'forcePlunger_R' 'bearingExtX_R' 'forceWall_R' 'forceCasingScrewX_R'...
    'forceCasingScrewY_R' 'forcePlungerScrewY_R' 'forceBearingExtY_R' 'forceBearingCasingScrew_R'...
    'thighMoment_R' 'Fspring_R' 'FpawlPinX_R' 'FpawlPinY_R' 'Fstring_R' 'shankForce_R' ...
    'F_cf_x_R' 'F_cf_y_R' 'GRF_fa_R' 'GRF_v_R' 'torque_Bearing_R' 'F_screwThigh_x_R' 'F_screwThigh_y_R'...
    'F_screwFoamT_x1_R' 'F_screwFoamT_x2_R' 'F_screwFoamT_y1_R' 'F_screwFoamT_y2_R'...
    'F_pawl_x_R' 'F_knee_y_R' 'F_knee_x_R' 'F_string_R' 'thighForce_R' 'gasSpringForceMatrix'...
    'forceLoadMatrix' 'x_string' 'F_screwFoamS_x1_R' 'F_screwFoamS_x2_R' 'F_screwFoamS_y1_R' 'F_screwFoamS_y2_R'...
    'F_ankle_x_R' 'F_ankle_y_R'};

%% Create All Force Structure Branches %%
%Description: Creates first degree branch of force strucutre
%Note: The 1 at the end of each component branch is used as a
%disambiguation from the actual object names.
%Ex: [forceStruct.aBolt1, forceStruct.attachmentPlate1,...]
for i = 1:length(components)  
    forceStruct.(components{i}) = [];
end

%% Force Calculations %%
%Desciption: Calls the respective force functions within each component's
%object class. The calculated forces are stored both in the force
%structure, as well as within the classes themselves.
%Note: Input obj args to calculations (ie. first arg) use the passed objects; Input force
%args use the structure property values
for i = 1:70
    %% Shelf %%
    forceStruct.shelf1.forceGSYmax(i) = calculateForceGSYMax(shelf, min(com_Acceleration));
    forceStruct.shelf1.forceHingeX(i) = calculateForceHingeX(shelf);
    [forceStruct.shelf1.forceGSXL(i),forceStruct.shelf1.forceGSXR(i), forceStruct.shelf1.forceGSYL(i), forceStruct.shelf1.forceGSYR(i)] =...
        calculateForceGS(shelf,i);
    %% Top Bracket%%
    forceStruct.topBracket_R1.forceGasSpringBracket1_x_R(i) =...
        calculateForceGasSpringBracket1_x(topBracket_R,forceStruct.shelf1.forceGSXR(i));
    forceStruct.topBracket_R1.forceGasSpringBracket1_y_R(i) =...
        calculateForceGasSpringBracket1_y(topBracket_R,forceStruct.shelf1.forceGSYR(i));
    forceStruct.topBracket_L1.forceGasSpringBracket1_x_L(i) =...
        calculateForceGasSpringBracket1_x(topBracket_L,forceStruct.shelf1.forceGSXL(i));
    forceStruct.topBracket_L1.forceGasSpringBracket1_y_L(i) =...
        calculateForceGasSpringBracket1_y(topBracket_L,forceStruct.shelf1.forceGSYL(i));
    %% Gas Spring Bolt %%
    forceStruct.gasSpringBolts1.forceGasSpringBolt1_x_R(i) =...
        calculateForceGasSpringBolt1_x(gasSpringBolts,forceStruct.topBracket_R1.forceGasSpringBracket1_x_R(i));
    forceStruct.gasSpringBolts1.forceGasSpringBolt1_y_R(i) =...
        calculateForceGasSpringBolt1_y(gasSpringBolts,forceStruct.topBracket_R1.forceGasSpringBracket1_y_R(i));
    forceStruct.gasSpringBolts1.forceGasSpringBolt1_x_L(i) =...
        calculateForceGasSpringBolt1_x(gasSpringBolts,forceStruct.topBracket_L1.forceGasSpringBracket1_x_L(i));
    forceStruct.gasSpringBolts1.forceGasSpringBolt1_y_L(i) =...
        calculateForceGasSpringBolt1_y(gasSpringBolts,forceStruct.topBracket_L1.forceGasSpringBracket1_y_L(i));
    %% Gas Springs %%
    forceStruct.gasSpring1.forceGasSpringBolt2_x_R(i) = ...
        calculateForceGasSpringBolt2_x(gasSpring,forceStruct.gasSpringBolts1.forceGasSpringBolt1_x_R(i));
    forceStruct.gasSpring1.forceGasSpringBolt2_y_R(i) = ...
        calculateForceGasSpringBolt2_y(gasSpring,forceStruct.gasSpringBolts1.forceGasSpringBolt1_y_R(i));
    forceStruct.gasSpring1.forceGasSpringBolt2_x_L(i) = ...
        calculateForceGasSpringBolt2_x(gasSpring,forceStruct.gasSpringBolts1.forceGasSpringBolt1_x_L(i));
    forceStruct.gasSpring1.forceGasSpringBolt2_y_L(i) = ...
        calculateForceGasSpringBolt2_y(gasSpring,forceStruct.gasSpringBolts1.forceGasSpringBolt1_y_L(i));
    %% Bottom Bracket %%
    forceStruct.bottomBracket_R1.forceBottom_x_R(i) = ...
        calculateForceBottom_x(bottomBracket_R,forceStruct.gasSpring1.forceGasSpringBolt2_x_R(i));
    forceStruct.bottomBracket_R1.forceBottom_y_R(i) = ...
        calculateForceBottom_y(bottomBracket_R,forceStruct.gasSpring1.forceGasSpringBolt2_y_R(i));
    forceStruct.bottomBracket_L1.forceBottom_x_L(i) = ...
        calculateForceBottom_x(bottomBracket_L,forceStruct.gasSpring1.forceGasSpringBolt2_x_L(i));
    forceStruct.bottomBracket_L1.forceBottom_y_L(i) = ...
        calculateForceBottom_y(bottomBracket_L,forceStruct.gasSpring1.forceGasSpringBolt2_y_L(i));
    %% Hip Member %%
    [forceStruct.hipMember1.FL1(i), forceStruct.hipMember1.FL2(i)] = ...
        calculateForceLoads(hipMember,forceStruct.bottomBracket_L1.forceBottom_y_L(i),forceStruct.bottomBracket_R1.forceBottom_y_R(i));
    %% Shaft AA %%
    %weightMember2 = hipMember2.hipMember2_Weight;
    forceStruct.shaftAA1.forceMember2_R(i) = ...
        calculateForceMember2(shaftAA,forceStruct.hipMember1.FL2(i),greaterTrochanter_AccelerationY(i));
    %% Bearing AA %%
    forceStruct.bearingAA1.forceCasingAbdY_R(i) = ...
        calculateForceCasingAbdY(bearingAA,forceStruct.shaftAA1.forceMember2_R(i));
    %% Hip Member 2 %%
    weightPlunger = plungerEF.plunger_Mass*9.81;
    weightBearingCasing = bearingCasingEF.bearingCasingEF_Mass*9.81;
    forceStruct.hipMember21.forceHip_R(i) = ...
        calculateForceHip(hipMember2,forceStruct.shaftAA1.forceMember2_R(i),greaterTrochanter_AccelerationY(i),weightPlunger...
        ,weightBearingCasing);
    forceStruct.hipMember21.torqueBearingABD_R(i) = ...
        calculateTorqueBearingABD(shaftAA,forceStruct.bottomBracket_L1.forceBottom_y_L(i),forceStruct.bottomBracket_R1.forceBottom_y_R(i)...
        ,forceStruct.hipMember1.FL2(i),30.14,34.53,abdAddHip_AngAcceleration(i),forceStruct.hipMember21.forceHip_R(i));
    %% Plunger EF Right %%
    forceStruct.plungerEF1.forcePlunger_R(i) = ...
        calculateForcePlunger(plungerEF,A4Hip_Angle(i));
    forceStruct.plungerEF1.bearingExtX_R(i) = ...
        calculateBearingExtX(plungerEF, greaterTrochanter_AccelerationX(i), 15);
    forceStruct.plungerEF1.forceWall_R(i) = ...
        calculateForceWall(plungerEF);
    forceStruct.plungerEF1.torque_Bearing_R(i) = ...
        calculateTorqueBearing(plungerEF,flxExtHip_AngAcceleration(i));
    %% Plunger Casing EF Right %%
    forceStruct.plungerCasingEF1.forceCasingScrewX_R(i) = ...
        calculateForceCasingScrewX(plungerCasingEF,15,greaterTrochanter_AccelerationX(i),forceStruct.plungerEF1.forcePlunger_R(i));
    forceStruct.plungerCasingEF1.forceCasingScrewY_R(i) = ...
        calculateForceCasingScrewX(plungerCasingEF,15,greaterTrochanter_AccelerationY(i),forceStruct.plungerEF1.forcePlunger_R(i));
    %% Plunger Screw EF Right %%
    forceStruct.plungerScrewEF1.forcePlungerScrewY_R(i) = ...
        calculateForcePlungerScrewY(plungerScrewEF,forceStruct.hipMember21.forceHip_R(i),forceStruct.plungerEF1.forcePlunger_R(i)...
        ,plungerEF.plunger_Mass,greaterTrochanter_AccelerationY(i));
    forceStruct.plungerScrewEF1.forceBearingExtY_R(i) = ...
        calculateForceBearingExtY(plungerScrewEF,15,forceStruct.plungerEF1.forcePlunger_R(i),31.04);
    %% Bearing Casing EF %%
    weightPlungerCasing = plungerCasingEF.plungerCasing_Mass*9.81;
    forceStruct.bearingCasingEF1.forceBearingCasingScrewY_R(i) = ...
        calculateForceBearingCasingScrewY(bearingCasingEF,greaterTrochanter_AccelerationY(i),forceStruct.plungerScrewEF1.forceBearingExtY_R(i)...
        ,weightPlunger,weightPlungerCasing);
    %% Thigh %%
    [forceStruct.exoThigh1.F_screwFoamT_y1_R(i),forceStruct.exoThigh1.F_screwFoam_y2_R(i),forceStruct.exoThigh1.F_pawl_x_R(i)...
        ,forceStruct.exoThigh1.F_knee_y_R(i),forceStruct.exoThigh1.F_knee_x_R(i),forceStruct.exoThigh1.thighMoment_R(i)] = ...
        calcThighForces(exoThigh, thigh_AccelerationX(i),thigh_AccelerationY(i),flxExtHip_AngAcceleration(i)...
        ,forceStruct.plungerScrewEF1.forcePlungerScrewY_R(i),forceStruct.plungerEF1.bearingExtX_R(i),forceStruct.plungerEF1.torque_Bearing_R(i)...
        ,momentHip(i),momentKnee(i));
    %% Pawl String %%
    forceStruct.pawlString1.x_string(i) = ...
        getXString(pawlString,ankle_Angle(i));
    %% Pawl Spring %%
    forceStruct.pawlSpring1.x_spring(i) = ...
        setXSpring(pawlSpring,forceStruct.pawlString1.x_string(i));
    forceStruct.pawlSpring1.Fspring_R(i) = ...
        getF_spring(pawlSpring,forceStruct.pawlSpring1.x_spring(i));
    %% Pawl %%
    forceStruct.pawl1.FpawlPinX_R(i) = ...
        getF_pawlPinX(pawl,forceStruct.exoThigh1.F_pawl_x_R(i));
    forceStruct.pawl1.FpawlPinY_R(i) = ...
        getF_pawlPinY(pawl,forceStruct.pawlSpring1.Fspring_R(i));
    forceStruct.pawl1.F_string_R(i) = ...
        getF_string(pawl,forceStruct.pawlSpring1.Fspring_R(i));
    %% Shank %%
    [forceStruct.exoShank1.F_screwFoamS_x1_R(i),forceStruct.exoShank1.F_screwFoamS_x2_R(i),forceStruct.exoShank1.F_screwFoamS_y1_R(i)...
        ,forceStruct.exoShank1.F_screwFoamS_y2_R(i),forceStruct.exoShank1.F_ankle_x_R(i),forceStruct.exoShank1.F_ankle_y_R(i)] = ...
        calcShankForces(exoShank,shank_AngAcceleration(i),shank_AccelerationY(i),forceStruct.exoThigh1.F_pawl_x_R(i)...
        ,forceStruct.exoThigh1.F_knee_x_R(i),forceStruct.exoThigh1.F_knee_y_R(i),momentKnee(i));
    %% Ubar %%
    forceStruct.uBar1.F_cf_x_R(i) = ...
        getF_cf_x(uBar,foot_AccelerationX(i),forceStruct.exoShank1.F_ankle_x_R(i));
    forceStruct.uBar1.F_cf_y_R(i) = ...
        getF_cf_y(uBar,foot_AccelerationY(i),forceStruct.exoShank1.F_ankle_y_R(i));
    %% Compliant Boot %%
    forceStruct.cBoot1.GRF_fa_R(i) = ...
        getGRF_fa(cBoot,foot_AccelerationX(i),forceStruct.uBar1.F_cf_x_R(i),i);
    forceStruct.cBoot1.GRF_v_R(i) = ...
        getGRF_v(cBoot,foot_AccelerationY(i),forceStruct.uBar1.F_cf_y_R(i),UserM,i);
    forceStruct.cBoot1.GRF_vexo_R(i) = ...
        getGRF_vEXO(cBoot,foot_AccelerationY(i),forceStruct.uBar1.F_cf_y_R(i),i);
end


end

