function [sfStruct] = CalculateSF(aBolt,attachmentPlate,bearingAA,bearingCasingEF,bottomBracket_L,bottomBracket_R...
                                                    ,exoThigh,uBar,exoShank,foamThigh,gasSpring,gasSpringBolts...
                                                    ,hipFlexExBearing,hipMember,hipMember2,hipSpring,hipStopper,hipStopperPin...
                                                    ,keys,kneePin,pawl,foamShank,pawlPin,pawlString,pawlSpring,plungerCasingEF...
                                                    ,plungerEF,plungerScrewEF,ratchet,shaftAA,shelf,thighScrew,shankScrew,topBracket_L...
                                                    ,topBracket_R,cBoot... 
                                                    ,flxExtHip_AngAcceleration,shank_AccelerationX,shank_AccelerationY,shank_AngAcceleration...
                                                    ,foot_AccelerationX,foot_AccelerationY,A4Hip_Acceleration,greaterTrochanter_AccelerationX...
                                                    ,greaterTrochanter_AccelerationY,com_Acceleration,abdAddHip_AngAcceleration,momentHip...
                                                    ,momentKnee,thigh_AccelerationX,thigh_AccelerationY,A4Hip_Angle,hip_Moment,ground_ReactionX...
                                                    ,ground_ReactionY,ankle_Angle,A3Thigh_AngAcceleration...
                                                    ,UserM,forceStruct)
%Calculate Safety Factors
%Written by: Matthew Choi
%Last updated: Nov. 26, 2019
%Input: All objects  and accelerations necessary to calculate safety factors, and a force
%structure
%Output: Safety factor structure containing the components and their
%derivative safety factors. The safety factors are across 70 frames, so
%they must be mapped across 100 frames (ie. gait %) externally. 
%Description: Takes the component objects and the previously populated
%force structure and calculates the safety factors per component force, and
%returns in in a safety factor structure. Does not call fatigue safety
%factors.
%Notes: Finish debugging and check over with mainMEGAN from old code

%% Component Names %%
components = {'aBolt1' 'attachmentPlate1' 'bearingAA1' 'bearingCasingEF1' 'bottomBracket_L1' 'bottomBracket_R1' 'exoThigh1' 'uBar1'...
                                                    'exoShank1' 'foamThigh1' 'gasSpring1' 'gasSpringBolts1' 'hipFlexExBearing1'...
                                                    'hipMember1' 'hipMember21' 'hipString1' 'hipStopper1' 'hipStopperPin1' 'keys1'...
                                                    'kneePin1' 'pawl1' 'foamShank1' 'pawlPin1' 'pawlString1' 'plungerCasingEF1' 'plungerEF1'...
                                                    'plungerScrewEF1' 'ratchet1' 'shaftAA1' 'shelf1' 'thighScrew1' 'shankScrew1' 'topBracket_L1'...
                                                    'topBracket_R1' 'cBoot1'};

%% Force Names %% (Not used)
forceNames = {'forceGSYmax' 'forceGSXL' 'forceGSYL' 'forceGSXR' 'forceGSYR' 'forceGasSpringBracket1_x_R'...
    'forceGasSpringBracket1_y_R' 'forceGasSpringBracket1_x_L' 'forceGasSpringBracket1_y_L'...
    'forceGasSpringBolt1_x_R' 'forceGasSpringBolt1_y_R' 'forceGasSpringBolt1_x_L' 'forceGasSpringBolt1_y_L'...
    'forceGasSpringBolt2_x_R' 'forceGasSpringBolt2_y_R' 'forceGasSpringBolt2_x_L' 'forceGasSpringBolt2_x_L'...
    'forceBottom_x_R' 'forceBottom_y_R' 'forceBottom_x_L' 'forceBottom_y_L' 'FL1' 'FL2'...
    'forceMember2_R' 'torqueBearingABD_R' 'forceBushingY_R' 'forceCasingAbdY_R'...
    'forceHip_R' 'forcePlunger_R' 'bearingExtX_R' 'forceWall_R' 'forceCasingScrewX_R'...
    'forceCasingScrewY_R' 'forcePlungerScrewY_R' 'forceBearingExtY_R' 'forceBearingCasingScrew_R'...
    'thighMoment_R' 'Fspring_R' 'FpawlPinX_R' 'FpawlPinY_R' 'Fstring_R' 'shankForce_R' ...
    'F_cf_x_R' 'F_cf_y_R' 'GRF_fa_R' 'GRF_v_R' 'torque_Bearing_R' 'F_screwThigh_x_R' 'F_screwThigh_y_R'...
    'F_screwFoamT_x1_R' 'F_screwFoamT_x2_R' 'F_screwFoamT_y1_R' 'F_screwFoamT_y2_R'...
    'F_pawl_x_R' 'F_knee_y_R' 'F_knee_x_R' 'F_string_R' 'thighForce_R' 'gasSpringForceMatrix'...
    'forceLoadMatrix' 'x_string' 'F_screwFoamS_x1_R' 'F_screwFoamS_x2_R' 'F_screwFoamS_y1_R' 'F_screwFoamS_y2_R'...
    'F_ankle_x_R' 'F_ankle_y_R'};

%% Safety Factor Names %%
sfNames = {'n_stress_shelf','n_stress_Bracket1_R','n_GasSpringBolt1_R','n_bottomBracket_R','n_stress','n_capacity_BearingAA_R'...
    ,'n_shear_hipStopper_R','n_stress_hipStopper_R','n_stress_ShaftAA_R','n_stress_keys_R','n_stress_HipMember2_R','n_stress_PlungerEF_R'...
    ,'n_stress_PlungerScrew_R','n_capacity_hipBearingEF_R','n_shear_hipSpring_R','n_stress_BearingCasingScrew_R','n_attachment_R'...
    ,'n_stress_thigh_R','n_foamTH_R','n_failure_kneeBushing_R','n_shear_kneePin_R','n_bending_ratchet_R','n_shear_Fspring_R'...
    ,'n_yield_Pawl_R','n_shear_pawlPin_R','n_supture_PawlString_R','nmin_shank_R','n_stress_ubar_R','n_bolt_Abolt_R'...
    ,'n_DE_Cboot_R'};

%% Create All Safety Factor Structure Branches %%
%Description: Creates first degree branch of safety factor structure.
%Note: The 1 at the end of each component branch is used as a
%disambiguation from the actual object names. 
%Ex: [sfStruct.aBolt1, sfStruct.attachmentPlate1,...]
for i = 1:length(components)
    sfStruct.(components{i}) = [];
end

%% Safety Factor Calculations %%
%Description: Calls the respective safety factor functions within each component's
%object class. The calculated safety factors are stored both in the safety
%factor structure, as well as within the classes themselves.
%Note: Input obj args to calculations (ie. first arg) use the passes
%objects; Input safety factor args use the structure property values. 
for i = 1:70
    %% Shelf %%
    sfStruct.shelf1.n_stress_shelf(i) = ...
        getn_stress(shelf,forceStruct.shelf1.forceGSYL(i),forceStruct.shelf1.forceGSYR(i));
    
    %% Top Bracket %%
    sfStruct.topBracket_R1.n_stress_Bracket1_R(i) = ...
        getn_stress(topBracket_R,forceStruct.topBracket_R1.forceGasSpringBracket1_x_R(i),forceStruct.topBracket_R1.forceGasSpringBracket1_y_R(i));
    
    %% Gas Spring Bolts %%
    sfStruct.gasSpringBolts1.n_GasSpringBolt1_R(i) = ...
        getbolt_n(gasSpringBolts, topBracket_R.TopBracket_W, topBracket_R.TopBracket_T, topBracket_R.TopBracket_L_BGS, 0.005, 0.008...
        ,0.006, 290000000, 290000000,forceStruct.gasSpringBolts1.forceGasSpringBolt1_x_R(i),forceStruct.gasSpringBolts1.forceGasSpringBolt1_y_R(i));
    %% Bottom Bracket %%
    sfStruct.bottomBracket_R1.n_bottomBracket_R(i) = ...
        bottomBracket_XYshearSF(bottomBracket_R, forceStruct.gasSpring1.forceGasSpringBolt2_x_R(i), forceStruct.gasSpring1.forceGasSpringBolt2_y_R(i));
    
    %% Hip Member %%
    sfStruct.hipMember1.n_stress(i) = ...
        getn_stress(hipMember,forceStruct.hipMember1.FL1(i),forceStruct.hipMember1.FL2(i));
    
    %% Bearing AA %%
    sfStruct.bearingAA1.n_capacity_BearingAA_R(i) = ...
        BearingAA_SF(bearingAA,forceStruct.bearingAA1.forceCasingAbdY_R(i));
    
    %% Hip Stopper Pin %%
    sfStruct.hipStopperPin1.n_shear_hipStopper_R(i) = ...
        hipStopperPin_shearSF(hipStopperPin, 0.1, abdAddHip_AngAcceleration(i));
    
    %% Hip Stopper %%
    sfStruct.hipStopper1.n_stress_hipStopper_R(i) = ...
        hipStopper_shearSF(hipStopper, 0.1, abdAddHip_AngAcceleration(i));
    
    %% Hip Member 2 %%
    weightPlunger = plungerEF.plunger_Mass*9.81;
    weightBearingCasing = bearingCasingEF.bearingCasingEF_Mass*9.81;
    weightPlungerCasing = plungerCasingEF.plungerCasing_Mass*9.81;
    sfStruct.hipMember21.n_stress_ShaftAA_R(i) = ...
        ShaftAA_SF(shaftAA, forceStruct.hipMember1.FL2(i),forceStruct.hipMember21.torqueBearingABD_R(i));
    sfStruct.hipMember21.n_stress_keys_R(i) = ...
        Keys_SF(keys, forceStruct.hipMember21.torqueBearingABD_R(i));
    sfStruct.hipMember21.n_stress_HipMember2_R(i) = ...
        getn_stress(hipMember2, forceStruct.shaftAA1.forceMember2_R(i), weightPlunger, weightBearingCasing...
        ,forceStruct.hipMember21.torqueBearingABD_R(i), 0.05, 2.25,forceStruct.hipMember21.forceHip_R(i));
    
    %% Plunger Screw EF Right %%
    sfStruct.plungerScrewEF1.n_stress_PlungerEF_R(i) = ...
        getn_stress(plungerEF, forceStruct.plungerScrewEF1.forceBearingExtY_R(i), 15, forceStruct.plungerEF1.forcePlunger_R(i)...
        ,forceStruct.plungerEF1.torque_Bearing_R(i));
    sfStruct.plungerScrewEF1.n_stress_PlungerScrew_R(i) = ...
        calculateSafetyFactor(plungerScrewEF,forceStruct.plungerScrewEF1.forcePlungerScrewY_R(i));
    sfStruct.plungerScrewEF1.n_capacity_hipBearingEF_R(i) = ...
        hipFlexExBearing_SF(hipFlexExBearing, forceStruct.plungerScrewEF1.forceBearingExtY_R(i));
    sfStruct.plungerScrewEF1.n_shear_hipSpring_R(i) = ...
        hipSpring_shearSF(hipSpring, forceStruct.plungerEF1.forcePlunger_R(i));
    
    %% Bearing Casing EF %%
    sfStruct.bearingCasingEF1.n_stress_BearingCasingScrew_R(i) = ...
        calculateSafetyFactor(bearingCasingEF, forceStruct.plungerScrewEF1.forceBearingExtY_R(i), weightPlunger, weightPlungerCasing...
        ,0.05);
    
    %% Attachment Plate %%
    sfStruct.attachmentPlate1.n_attachment_R(i) = ...
        hipAttachPlate_ruptureSF(attachmentPlate, weightPlungerCasing, forceStruct.plungerEF1.forcePlunger_R(i), 15);
    
    %% Thigh %%
    sfStruct.exoThigh1.n_stress_thigh_R(i) = ...
        calcSF(exoThigh,forceStruct.exoThigh1.F_pawl_x_R(i),forceStruct.exoThigh1.F_knee_x_R(i),forceStruct.exoThigh1.F_knee_y_R(i)...
        ,forceStruct.plungerEF1.bearingExtX_R(i),forceStruct.plungerScrewEF1.forcePlungerScrewY_R(i));
    sfStruct.exoThigh1.n_foamTH_R(i) = ...
        calcSF(foamThigh, forceStruct.exoThigh1.F_knee_y_R(i));
%     sfStruct.exoThigh1.n_failure_kneeBushing_R(i) = ...
%         kneeBushing_SF(kneeBushing, forceStruct.exoThigh1.F_knee_x_R(i), forceStruct.exoThigh1.F_knee_y_R(i));
    sfStruct.exoThigh1.n_shear_kneePin_R(i) = ...
        kneePin_shearSF(kneePin, forceStruct.exoThigh1.F_knee_x_R(i), forceStruct.exoThigh1.F_knee_y_R(i));
    sfStruct.exoThigh1.n_bending_ratchet_R(i) = ...
        ratchet_bendingSF(ratchet, forceStruct.exoThigh1.F_pawl_x_R(i));
    
    %% Pawl Spring %%
    sfStruct.pawlSpring1.n_shear_Fspring_R(i) = ...
        pawlSpring_shearSF(pawlSpring,forceStruct.pawlSpring1.Fspring_R(i));
    
    %% Pawl %%
    sfStruct.pawl1.n_yield_Pawl_R(i) = ...
        pawl_yieldSF(pawl,forceStruct.pawl1.FpawlPinX_R(i));
    sfStruct.pawl1.n_shear_pawlPin_R(i) = ...
        pawlPin_shearSF(pawlPin, forceStruct.pawl1.FpawlPinX_R(i), forceStruct.pawl1.FpawlPinY_R(i));
    
    %% Pawl String %%
    sfStruct.pawlString1.n_rupture_PawlString(i) = ...
        string_ruptureSF(pawlString, forceStruct.pawl1.F_string_R(i));
    
    %% Shank %%
    sfStruct.exoShank1.nmin_shank_R(i) = ...
        calcSF(exoShank,forceStruct.exoShank1.F_ankle_x_R(i),forceStruct.exoShank1.F_ankle_y_R(i),forceStruct.exoThigh1.F_knee_x_R(i)...
        ,forceStruct.exoThigh1.F_knee_y_R(i),forceStruct.pawl1.FpawlPinX_R(i));
    sfStruct.exoShank1.n_foamSH_R(i) = ...
        calcSF(foamShank, forceStruct.exoThigh1.F_knee_y_R(i));
    
    %% Thigh and Shank Screw %%
    sfStruct.thighScrew1.n_thighScrew(i) = ...
        calcSF(thighScrew,max([forceStruct.exoThigh1.F_screwFoamT_y1_R(i),forceStruct.exoThigh1.F_screwFoam_y2_R(i)...
        ,forceStruct.exoThigh1.F_knee_y_R(i)]));
    sfStruct.shankScrew1.n_shankScrew(i) = ...
        calcSF(shankScrew,max([forceStruct.exoShank1.F_screwFoamS_y1_R(i),forceStruct.exoShank1.F_screwFoamS_y2_R(i)...
        ,forceStruct.exoShank1.F_ankle_y_R(i)]));
    
    %% Ubar %%
    sfStruct.uBar1.n_stress_ubar_R(i) = ...
        calcn_stress(uBar, 3.5,forceStruct.uBar1.F_cf_x_R(i),forceStruct.uBar1.F_cf_y_R(i),forceStruct.exoShank1.F_ankle_x_R(i));
    sfStruct.uBar1.n_bolt_Abolt_R(i) = ...
        getbolt_n(aBolt, uBar,  exoShank.W_shank, exoShank.t_total, exoShank.L_shank, exoShank.shank_Sy);
    
    %% Compliant Boot %%
    sfStruct.cBoot1.n_DE_Cboot_R(i) = ...
        CBoot_distortionNRG(cBoot, UserM,forceStruct.cBoot1.GRF_v_R(i),forceStruct.cBoot1.GRF_fa_R(i),forceStruct.uBar1.F_cf_y_R(i));
end
end

