function [forceStruct,sfStruct,fatigueStruct,paramFlag] = Parameterize(aBolt,attachmentPlate,bearingAA,bearingCasingEF,bottomBracket_L,bottomBracket_R...
                                                    ,exoThigh,uBar,exoShank,foamThigh,gasSpring,gasSpringBolts...
                                                    ,hipFlexExBearing,hipMember,hipMember2,hipSpring,hipStopper,hipStopperPin...
                                                    ,keys,kneePin,pawl,foamShank,pawlPin,pawlString,pawlSpring,plungerCasingEF...
                                                    ,plungerEF,plungerScrewEF,ratchet,shaftAA,shelf,thighScrew,shankScrew,topBracket_L...
                                                    ,topBracket_R,cBoot... 
                                                    ,flxExtHip_AngAcceleration,shank_AccelerationX,shank_AccelerationY,shank_AngAcceleration...
                                                    ,foot_AccelerationX,foot_AccelerationY,A4Hip_Acceleration,greaterTrochanter_AccelerationX...
                                                    ,greaterTrochanter_AccelerationY,com_Acceleration,abdAddHip_AngAcceleration,momentHip...
                                                    ,momentKnee,thigh_AccelerationX,thigh_AccelerationY,A4Hip_Angle,hip_Moment,ground_ReactionX...
                                                    ,ground_ReactionY,ankle_Angle,A3Thigh_AngAcceleration,UserM...
                                                    ,limitingSF,limitingSFValue,limitingSFComponent)
%Parameterize
%Written by: Matthew Choi
%Last updated: Nov. 30, 2019
%Input: All objects, accelerations, and name of limiting safety factor.
%Output: Structures containing forces, safety factors, fatigue safety
%factors, and minimum safety factors. Also returns a boolean flag
%controlling if parameterization should be continued or not.
%Description: Populates the force and safety factor structures, and
%compares the selected limiting safety factor to the acceptable design
%range/value. Returns the structures and a boolean continuation flag. 
%Notes: Finish debugging and test

%% Populate Structures %%
forceStruct = CalculateForces(aBolt,attachmentPlate,bearingAA,bearingCasingEF,bottomBracket_L,bottomBracket_R...
                                                    ,exoThigh,uBar,exoShank,foamThigh,gasSpring,gasSpringBolts...
                                                    ,hipFlexExBearing,hipMember,hipMember2,hipSpring,hipStopper,hipStopperPin...
                                                    ,keys,kneePin,pawl,foamShank,pawlPin,pawlString,pawlSpring,plungerCasingEF...
                                                    ,plungerEF,plungerScrewEF,ratchet,shaftAA,shelf,thighScrew,shankScrew,topBracket_L...
                                                    ,topBracket_R,cBoot... 
                                                    ,flxExtHip_AngAcceleration,shank_AccelerationX,shank_AccelerationY,shank_AngAcceleration...
                                                    ,foot_AccelerationX,foot_AccelerationY,A4Hip_Acceleration,greaterTrochanter_AccelerationX...
                                                    ,greaterTrochanter_AccelerationY,com_Acceleration,abdAddHip_AngAcceleration,momentHip...
                                                    ,momentKnee,thigh_AccelerationX,thigh_AccelerationY,A4Hip_Angle,hip_Moment,ground_ReactionX...
                                                    ,ground_ReactionY,ankle_Angle,A3Thigh_AngAcceleration...
                                                    ,UserM);
sfStruct = CalculateSF(aBolt,attachmentPlate,bearingAA,bearingCasingEF,bottomBracket_L,bottomBracket_R...
                                                    ,exoThigh,uBar,exoShank,foamThigh,gasSpring,gasSpringBolts...
                                                    ,hipFlexExBearing,hipMember,hipMember2,hipSpring,hipStopper,hipStopperPin...
                                                    ,keys,kneePin,pawl,foamShank,pawlPin,pawlString,pawlSpring,plungerCasingEF...
                                                    ,plungerEF,plungerScrewEF,ratchet,shaftAA,shelf,thighScrew,shankScrew,topBracket_L...
                                                    ,topBracket_R,cBoot... 
                                                    ,flxExtHip_AngAcceleration,shank_AccelerationX,shank_AccelerationY,shank_AngAcceleration...
                                                    ,foot_AccelerationX,foot_AccelerationY,A4Hip_Acceleration,greaterTrochanter_AccelerationX...
                                                    ,greaterTrochanter_AccelerationY,com_Acceleration,abdAddHip_AngAcceleration,momentHip...
                                                    ,momentKnee,thigh_AccelerationX,thigh_AccelerationY,A4Hip_Angle,hip_Moment,ground_ReactionX...
                                                    ,ground_ReactionY,ankle_Angle,A3Thigh_AngAcceleration...
                                                    ,UserM,forceStruct);
fatigueStruct = CalculateFatigue(aBolt,attachmentPlate,bearingAA,bearingCasingEF,bottomBracket_L,bottomBracket_R...
                                                    ,exoThigh,uBar,exoShank,foamThigh,gasSpring,gasSpringBolts...
                                                    ,hipFlexExBearing,hipMember,hipMember2,hipSpring,hipStopper,hipStopperPin...
                                                    ,keys,kneePin,pawl,foamShank,pawlPin,pawlString,pawlSpring,plungerCasingEF...
                                                    ,plungerEF,plungerScrewEF,ratchet,shaftAA,shelf,thighScrew,shankScrew,topBracket_L...
                                                    ,topBracket_R,cBoot... 
                                                    ,flxExtHip_AngAcceleration,shank_AccelerationX,shank_AccelerationY,shank_AngAcceleration...
                                                    ,foot_AccelerationX,foot_AccelerationY,A4Hip_Acceleration,greaterTrochanter_AccelerationX...
                                                    ,greaterTrochanter_AccelerationY,com_Acceleration,abdAddHip_AngAcceleration,momentHip...
                                                    ,momentKnee,thigh_AccelerationX,thigh_AccelerationY,A4Hip_Angle,hip_Moment,ground_ReactionX...
                                                    ,ground_ReactionY,ankle_Angle,A3Thigh_AngAcceleration...
                                                    ,forceStruct);
%% Safety Factor Check %%
if(isfield(fatigueStruct.(limitingSFComponent),(limitingSF))) %If fatigue struct entry
    if(fatigueStruct.(limitingSFComponent).(limitingSF) < limitingSFValue) %If safety factor too low
        paramFlag = true;
    else %Safety factor is in acceptable range/value
        paramFlag = false;
    end
else %Safety factor struct entry
    if(min(sfStruct.(limitingSFComponent).(limitingSF)) < limitingSFValue) %If safety factor too low
        paramFlag = true;
    else %Safety factor is in acceptable range/value
        paramFlag = false;
    end
end
end

